#!/bin/bash
# This hook is run after every virtualenv is deactivated.

# django-admin.py will attempt to use a settings file if this variable
# is set.  This is usually only desirable in the particular environment,
# so it is unset on deactivate to avoid unexpected behavior.
unset DJANGO_SETTINGS_MODULE