#!/bin/bash
# This hook is run after every virtualenv is activated.

# echo "running global postactivate"

# This file uses variables ($VARIABLENAME) defined in EmceeVirtualEnv_config
# to allow customization of the specific commands

# pull from the config file
source $WORKON_HOME/EmceeVirtualEnv_config

# activate the venv file
if [ -f $MCV_VENV_NAME ]; then
    source $MCV_VENV_NAME
fi


###########
# Aliases #
###########

# these aliases depend on the DJANGO_SETTINGS_MODULE environment variable,
# so it checks to see if it's set before making the aliases.
# if it's not found, the aliases fall back to manage.py

if [ $DJANGO_SETTINGS_MODULE ]; then
    alias $DJ_ALIAS_NAME="django-admin.py"
    alias $DJRUN_ALIAS_NAME="django-admin.py runserver"
else
    # echo "DJANGO_SETTINGS_MODULE is not set, add it to your venv file.
# Falling back to manage.py"
    alias $DJ_ALIAS_NAME="python manage.py"
    alias $DJRUN_ALIAS_NAME="python manage.py runserver"
fi

## add other aliases you want available here.
## For example, I use a couple heroku-specific aliases:
# alias hrun="heroku run"
# alias hdj="heroku run python manage.py"