#!/bin/bash
# This file is run whenever you activate this virtualenv.
# Add environment variables and local aliases here

export DJANGO_SECRET_KEY='1of*b8rert1h^yxfte1kkl3tr#_k+orinrbw(d!p_=l6bd(v#2'
export DJANGO_DEBUG="True"
export DJANGO_ENV="DEV"

# ------------------
# EmceeVirtualEnv generated stuff:

export DJANGO_PROJECT_ROOT=/home/ethan/development/myproject/
export PATH=$PATH:$DJANGO_PROJECT_ROOT
export DJANGO_SETTINGS_MODULE=myproject.settings
